export const blogDatas = [
    {
        id: 0,
        title: 'Exploring the Wonders of Machine Learning',
        category: 'Technology',
        summary: 'Dive into the fascinating world of machine learning and its applications.',
        imgSrc: 'https://picsum.photos/800/400/?image=1',
    },
    {
        id: 1,
        title: 'Healthy Living: A Guide to Balanced Nutrition',
        category: 'Health and Wellness',
        summary: 'Discover the secrets to maintaining a healthy lifestyle through balanced nutrition.',
        imgSrc: 'https://picsum.photos/800/400/?image=2',
    },
    {
        id: 2,
        title: 'Travel Diaries: A Journey Through Exotic Lands',
        category: 'Travel',
        summary: 'Embark on a virtual journey through breathtaking landscapes and vibrant cultures.',
        imgSrc: 'https://picsum.photos/800/400/?image=3',
    },
    {
        id: 3,
        title: 'The Art of Photography: Capturing Moments in Time',
        category: 'Art and Creativity',
        summary: 'Explore the beauty of photography and its ability to freeze moments in time.',
        imgSrc: 'https://picsum.photos/800/400/?image=4',
    },
    {
        id: 4,
        title: 'Coding Tips and Tricks for Web Developers',
        category: 'Programming',
        summary: 'Level up your web development skills with these handy coding tips and tricks.',
        imgSrc: 'https://picsum.photos/800/400/?image=5',
    },
    {
        id: 5,
        title: 'Mindfulness Meditation: A Path to Inner Peace',
        category: 'Wellness',
        summary: 'Learn about the practice of mindfulness meditation and its benefits for mental well-being.',
        imgSrc: 'https://picsum.photos/800/400/?image=6',
    },
    {
        id: 6,
        title: 'Mastering the Art of Cooking: Culinary Adventures Await!',
        category: 'Food and Cooking',
        summary: 'Embark on a culinary journey and discover the joy of cooking with passion.',
        imgSrc: 'https://picsum.photos/800/400/?image=8',
    },
    {
        id: 7,
        title: 'Creative Writing: Unleashing Your Imagination',
        category: 'Writing',
        summary: 'Unlock the power of your imagination through the art of creative writing and storytelling.',
        imgSrc: 'https://picsum.photos/800/400/?image=11',
    },
    {
        id: 8,
        title: 'The History of Space Exploration: From Earth to the Cosmos',
        category: 'Science',
        summary: 'Take a historical journey through the milestones of space exploration and discovery.',
        imgSrc: 'https://picsum.photos/800/400/?image=12',
    },
    {
        id: 9,
        title: 'DIY Home Decor: Transforming Spaces with Creativity',
        category: 'Home and Living',
        summary: 'Learn how to add a personal touch to your living space with creative and budget-friendly DIY decor ideas.',
        imgSrc: 'https://picsum.photos/800/400/?image=13',
    },
    {
        id: 10,
        title: 'Financial Planning 101: Building a Secure Future',
        category: 'Finance',
        summary: 'Get started on the path to financial security with essential tips and strategies for effective financial planning.',
        imgSrc: 'https://picsum.photos/800/400/?image=14',
    },
    {
        id: 11,
        title: 'The World of Vintage Cars: Nostalgia on Wheels',
        category: 'Automobiles',
        summary: 'Take a ride through the history and charm of vintage cars, capturing the essence of a bygone era.',
        imgSrc: 'https://picsum.photos/800/400/?image=15',
    },
    {
        id: 12,
        title: 'The Science Behind Climate Change',
        category: 'Science',
        summary: 'Delve into the scientific facts and consequences of climate change on our planet.',
        imgSrc: 'https://picsum.photos/800/400/?image=7',
    },

    {
        id: 13,
        title: 'Innovations in Artificial Intelligence: Shaping the Future',
        category: 'Technology',
        summary: 'Explore the latest breakthroughs and innovations in the field of artificial intelligence.',
        imgSrc: 'https://picsum.photos/800/400/?image=9',
    },
    {
        id: 14,
        title: 'Fitness Essentials: Building a Stronger, Healthier You',
        category: 'Fitness',
        summary: 'Discover the essential components of a successful fitness journey for a healthier lifestyle.',
        imgSrc: 'https://picsum.photos/800/400/?image=10',
    },
]
